# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='token')),
                ('lastTime', models.DateTimeField(auto_now=True)),
                ('expire', models.BigIntegerField(verbose_name='expire')),
            ],
            options={
                'db_table': 'bio_usersafety',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userName', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('isConfirmed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bio_user',
                'managed': False,
            },
        ),
    ]
