# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-08 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene_Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_name', models.CharField(max_length=64)),
                ('disease_name', models.CharField(max_length=64)),
                ('disease_class', models.CharField(max_length=64)),
                ('paper_id', models.IntegerField()),
            ],
            options={
                'db_table': 'bio_gene_disease',
            },
        ),
    ]
