# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projectManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper_Gene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(max_length=32)),
                ('paper_name', models.CharField(max_length=255)),
                ('paper_keyword', models.CharField(default=None, max_length=255)),
                ('paper_abstract', models.TextField()),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectManage.Gene')),
            ],
            options={
                'db_table': 'bio_paper_gene',
            },
        ),
    ]
